In [1]:
from jupyterthemes import get_themes
import jupyterthemes as jt
from jupyterthemes.stylefx import set_nb_theme

set_nb_theme('chesterish')

In [2]:
import pandas as pd   # Series and DataFrames

In [38]:
list1 = [3,5,7,9]

In [39]:
x = pd.Series(list1)

In [40]:
type(x)

pandas.core.series.Series

In [41]:
x

0    3
1    5
2    7
3    9
dtype: int64

In [42]:
x[2]

7

In [43]:
x = pd.Series(list1, index=['a','b','c','d'])  # Customize index
x

a    3
b    5
c    7
d    9
dtype: int64

In [44]:
x[1]

5

In [45]:
x['b']

5

In [46]:
y = pd.Series([12,14], index= ['r','j'])
y

r    12
j    14
dtype: int64

In [47]:
z = x.append(y)
z

C:\Users\Dell\AppData\Local\Temp\ipykernel_9940\2386576799.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  z = x.append(y)

a     3
b     5
c     7
d     9
r    12
j    14
dtype: int64

In [48]:
x = x.append(y)
x

C:\Users\Dell\AppData\Local\Temp\ipykernel_9940\3791096366.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  x = x.append(y)

a     3
b     5
c     7
d     9
r    12
j    14
dtype: int64

In [49]:
# DataFrame -> 2D data structure
# List method -> row wise (1. age, name, gender) (2.  age, name, gender)
# Dictionary method -> column wise (1. age, age) (2. name, name) (3. gender, gender)

In [50]:
# Row wise
x = [['Tushar',25,'Male'],['Abcd',26,'Female'],['Pqr',24,'Female']]

In [51]:
df1 = pd.DataFrame(x, columns=['Name','Age','Gender'])

In [52]:
df1

     Name  Age  Gender
0  Tushar   25    Male
1    Abcd   26  Female
2     Pqr   24  Female

In [53]:
# Column wise
s = {'Player':['Tushar','Virat','Dhoni'], 'Team':['MI','RCB','CSK'], 'Score':[100,85,96]}
s

{'Player': ['Tushar', 'Virat', 'Dhoni'],
 'Team': ['MI', 'RCB', 'CSK'],
 'Score': [100, 85, 96]}

In [54]:
df2 = pd.DataFrame(s)
df2

   Player Team  Score
0  Tushar   MI    100
1   Virat  RCB     85
2   Dhoni  CSK     96

In [55]:
df = pd.read_excel('ERPData.xlsx')

In [56]:
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [57]:
df.shape

(50, 3)

In [58]:
df.shape[0]

50

In [59]:
df.shape[1]

3

In [60]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [61]:
df.tail()

   MaterialID Location  Quantity
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [62]:
df.head(8)

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36
5    TMI-43T    MWH-4        78
6    TMI-43T    MWH-4        31
7    TMI-43T    MWH-2        29

In [63]:
df1

     Name  Age  Gender
0  Tushar   25    Male
1    Abcd   26  Female
2     Pqr   24  Female

In [64]:
new_df = pd.DataFrame(data=[['Ashwin',29,'Male'],['Rohini',24,'Female']], columns=df1.columns)
new_df

     Name  Age  Gender
0  Ashwin   29    Male
1  Rohini   24  Female

In [65]:
df1 = df1.append(new_df)
df1

C:\Users\Dell\AppData\Local\Temp\ipykernel_9940\1232835884.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(new_df)

     Name  Age  Gender
0  Tushar   25    Male
1    Abcd   26  Female
2     Pqr   24  Female
0  Ashwin   29    Male
1  Rohini   24  Female

In [66]:
df1.index = range(df1.shape[0])  # df1.shape -> (5, 3)  # df1.shape[0] -> 5  # range(5) -> (0, 5)

In [67]:
df1

     Name  Age  Gender
0  Tushar   25    Male
1    Abcd   26  Female
2     Pqr   24  Female
3  Ashwin   29    Male
4  Rohini   24  Female

In [73]:
x = ['A','B','C','D','E']

In [74]:
df1['Grades'] = x

In [70]:
df1

     Name  Age  Gender Grades
0  Tushar   25    Male      A
1    Abcd   26  Female      B
2     Pqr   24  Female      C
3  Ashwin   29    Male      D
4  Rohini   24  Female      E

In [79]:
df1.drop(['Gender','Age'], axis=1)

     Name Grades
0  Tushar      A
1    Abcd      B
2     Pqr      C
3  Ashwin      D
4  Rohini      E

In [80]:
df1

     Name  Age  Gender Grades
0  Tushar   25    Male      A
1    Abcd   26  Female      B
2     Pqr   24  Female      C
3  Ashwin   29    Male      D
4  Rohini   24  Female      E

In [81]:
df1.drop([1,3], axis=0)

     Name  Age  Gender Grades
0  Tushar   25    Male      A
2     Pqr   24  Female      C
4  Rohini   24  Female      E

In [82]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [87]:
df['Quantity']

0      34
1      67
2      27
3      65
4      36
5      78
6      31
7      29
8      10
9     120
10     34
11     58
12     76
13     32
14     65
15     87
16     12
17    102
18     34
19     52
20     39
21     75
22     48
23     71
24    152
25    109
26     57
27     83
28     34
29     57
30     27
31     65
32     43
33    112
34     26
35     31
36     28
37     65
38     70
39    145
40     34
41     57
42     31
43     38
44     42
45     69
46     85
47     29
48     75
49     39
Name: Quantity, dtype: int64

In [89]:
import numpy as np

In [90]:
ind = np.where(df.Quantity <= 50)
ind

(array([ 0,  2,  4,  6,  7,  8, 10, 13, 16, 18, 20, 22, 28, 30, 32, 34, 35,
        36, 40, 42, 43, 44, 47, 49], dtype=int64),)

In [91]:
scrap = df.iloc[ind]  # iloc -> selecting particular rows

In [92]:
scrap.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
2    LXCV-21    MWH-2        27
4    AXCP-78    MWH-4        36
6    TMI-43T    MWH-4        31
7    TMI-43T    MWH-2        29

In [94]:
scrap.shape

(24, 3)

In [99]:
ind1 = np.where((df.Location == 'MWH-2') & (df.Quantity <=50))
ind1

(array([ 2,  7,  8, 35, 36, 42], dtype=int64),)

In [103]:
mydf = df.iloc[ind1]
mydf

   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31

In [104]:
scrap = df.iloc[ind]

In [105]:
scrap.shape

(24, 3)

In [107]:
useful = df.drop(ind[0])
useful.shape

(26, 3)

In [108]:
useful.head()

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
3     AXCP-78    MWH-5        65
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
11    SDRT-67    MWH-4        58

In [110]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [111]:
# How many pieces in MWH-4 Quantity more than 70Kg
ind2 = np.where((df.Location == 'MWH-4') & (df.Quantity > 70))

In [122]:
scrap2 = df.iloc[ind2]

In [123]:
scrap2

   MaterialID Location  Quantity
5     TMI-43T    MWH-4        78
12    TMI-43T    MWH-4        76
21    TMI-43T    MWH-4        75

In [126]:
scrap2.shape[1]

3

In [127]:
((df.Location == 'MWH-4') & (df.Quantity > 70)).sum()

3

In [139]:
scrap

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
2     LXCV-21    MWH-2        27
4     AXCP-78    MWH-4        36
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
10    SDRT-67    MWH-1        34
13    TMI-43T    MWH-4        32
16    SDRT-67    MWH-5        12
18    TMI-43T    MWH-4        34
20    TMI-43T    MWH-4        39
22    DDBN-89    MWH-4        48
28    LXCV-21    MWH-5        34
30    DDBN-89    MWH-4        27
32    TMI-43T    MWH-4        43
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
40    DDBN-89    MWH-1        34
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
47    AXCP-78    MWH-3        29
49    DDBN-89    MWH-1        39

In [132]:
scrap.iloc[[0,1]]

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
2    LXCV-21    MWH-2        27

In [133]:
scrap.to_excel('Scrap.xlsx')

In [136]:
scrap.iloc[0,1]

'MWH-4'

In [138]:
len(scrap)

24

In [142]:
df1 = pd.read_excel('employees.xlsx')
df1

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [143]:
# Cleaning of excel file

In [144]:
op = np.where(df1['Deptt'].isnull())
op

(array([3, 5], dtype=int64),)

In [147]:
op1 = np.where(df1.Deptt.isnull())
op1

(array([3, 5], dtype=int64),)

In [ ]:
# What is difference between -> df1['Deptt'] and df1.Deptt

In [149]:
op2 = np.where((df1['EmpID'].isnull()) & (df1['Deptt'].isnull()))
op2

(array([5], dtype=int64),)

In [150]:
op3 = np.where((df1.EmpID.isnull()) & (df1.Deptt.isnull()))
op3

(array([5], dtype=int64),)

In [151]:
op4 = np.where((df1.EmpID.isnull()) | (df1.Deptt.isnull()))
op4

(array([3, 5, 6], dtype=int64),)

In [154]:
op5 = np.where((df1.Name.notnull()) & (df1.EmpID.notnull()))
op5

(array([0, 1, 3, 4], dtype=int64),)

In [155]:
op6 = np.where((df1.Name.notnull()) | (df1.EmpID.notnull()))
op6

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)

In [ ]:
# ind
# drop -> ind[0]

In [164]:
df1

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [165]:
new_df = df1.dropna()  # Any record/rows has null value gets removed
new_df

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
4    Rishi  R475    Prodn  DF453278

In [178]:
df = pd.read_excel('airquality.xlsx')
df.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
0   41.0    190.0   7.4    67      5    1
1   36.0    118.0   8.0    72      5    2
2   12.0    149.0  12.6    74      5    3
3   18.0    313.0  11.5    62      5    4
4    NaN      NaN  14.3    56      5    5

In [171]:
op1 = np.where((df['Ozone'].notnull()) & (df['Solar.R'].notnull()))
op1

(array([  0,   1,   2,   3,   6,   7,   8,  11,  12,  13,  14,  15,  16,
         17,  18,  19,  20,  21,  22,  23,  27,  28,  29,  30,  37,  39,
         40,  43,  46,  47,  48,  49,  50,  61,  62,  63,  65,  66,  67,
         68,  69,  70,  72,  73,  75,  76,  77,  78,  79,  80,  81,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  98,  99, 100,
        103, 104, 105, 107, 108, 109, 110, 111, 112, 113, 115, 116, 117,
        119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
        145, 146, 147, 148, 150, 151, 152], dtype=int64),)

In [172]:
op2 = np.where((df['Ozone'].notnull()) | (df['Solar.R'].notnull()))
op2

(array([  0,   1,   2,   3,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
         41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
        106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
        119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
        132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
        145, 146, 147, 148, 149, 150, 151, 152], dtype=int64),)

In [173]:
op3 = df.iloc[op1]
op3

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
6     23.0    299.0   8.6    65      5    7
..     ...      ...   ...   ...    ...  ...
147   14.0     20.0  16.6    63      9   25
148   30.0    193.0   6.9    70      9   26
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[111 rows x 6 columns]

In [174]:
op4 = df.iloc[op2]
op4

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
5     28.0      NaN  14.9    66      5    6
..     ...      ...   ...   ...    ...  ...
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[151 rows x 6 columns]

In [176]:
ind = np.where((df['Ozone'].isnull()) | (df["Solar.R"].isnull()))
df = df.drop(ind[0])
df

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
6     23.0    299.0   8.6    65      5    7
..     ...      ...   ...   ...    ...  ...
147   14.0     20.0  16.6    63      9   25
148   30.0    193.0   6.9    70      9   26
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[111 rows x 6 columns]

In [180]:
df1

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN      NaN  ER534867
6   Deepak   NaN  Quality  RF453432

In [181]:
ind = np.where(df1['Passport'].duplicated(keep=False))
ind

(array([0, 2, 3, 4, 6], dtype=int64),)

In [182]:
dup = df1.iloc[ind]
dup

     Name EmpID    Deptt  Passport
0  Sudeep  A342  Quality  DF453278
2     NaN  J436    Admin  DF453278
3   Arjun  A342      NaN  RF453432
4   Rishi  R475    Prodn  DF453278
6  Deepak   NaN  Quality  RF453432

In [184]:
non_dup = df1.drop(ind[0])
non_dup

      Name EmpID  Deptt  Passport
1  Ruchika  C578  Sales  CA567657
5   Chetan   NaN    NaN  ER534867

In [185]:
df

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      NaN      NaN  14.3    56      5    5
..     ...      ...   ...   ...    ...  ...
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[153 rows x 6 columns]

In [196]:
op = np.where((df['Temp'] <= 85) & (df['Temp'] >= 65))
op

(array([  0,   1,   2,   5,   6,   9,  10,  11,  12,  13,  16,  18,  21,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  43,  44,
         45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59,  60,  61,  62,  63,  64,  65,  66,  71,  72,  73,  75,
         76,  77,  78,  80,  81,  82,  83,  85,  86,  90,  91,  92,  93,
         94,  96, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
        115, 116, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 144, 145, 146, 148, 149, 150, 151, 152],
       dtype=int64),)

In [197]:
ind = df.iloc[op]
ind

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
5     28.0      NaN  14.9    66      5    6
6     23.0    299.0   8.6    65      5    7
..     ...      ...   ...   ...    ...  ...
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[103 rows x 6 columns]

In [198]:
len(ind)

103

In [200]:
df

     Ozone  Solar.R  Wind  Temp  Month  Day
0     41.0    190.0   7.4    67      5    1
1     36.0    118.0   8.0    72      5    2
2     12.0    149.0  12.6    74      5    3
3     18.0    313.0  11.5    62      5    4
4      NaN      NaN  14.3    56      5    5
..     ...      ...   ...   ...    ...  ...
148   30.0    193.0   6.9    70      9   26
149    NaN    145.0  13.2    77      9   27
150   14.0    191.0  14.3    75      9   28
151   18.0    131.0   8.0    76      9   29
152   20.0    223.0  11.5    68      9   30

[153 rows x 6 columns]

In [203]:
ex = pd.read_excel('ERPData.xlsx')
ex.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
# Checkpoints for PAN
# 1. 5 characters need to be an alphabet
# 2. 6th to 9th character should be a number
# 3. 10th character needs to be alphabet
# 4. Total characters = 10

# ERTGH1234R
# WERT56348L
# QWERT123TH

# o/p -> index(1,2) or pannumber itself

In [ ]:
# s1 = 'ERTGH1234R'
# s2 = 'WERT56348L'
# s3 = 'QWERT123TH'

# Tryyy

In [205]:
ex.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [206]:
grp1 = ex.groupby('Location')

In [208]:
grp1.groups

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}

In [209]:
len(grp1.groups)

5

In [210]:
for x,y in grp1:
    print(x,y)

MWH-1    MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39
MWH-2    MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
MWH-3    MaterialID Location  Quantity
14    TMI-43T    MWH-3        65
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
47    AXCP-78    MWH-3        29
MWH-4    MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
MWH-5    MaterialID Location  Quantity
3     AXCP-78    MWH-5        65
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
23    DDBN-89    MWH-5        71
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70

In [214]:
m = [6,9,8,7]
np.mean(m)

7.5

In [211]:
grp1.agg(np.mean)

           Quantity
Location
MWH-1     80.818182
MWH-2     44.111111
MWH-3     43.500000
MWH-4     48.533333
MWH-5     63.363636

In [212]:
grp1.aggregate(np.mean)

           Quantity
Location
MWH-1     80.818182
MWH-2     44.111111
MWH-3     43.500000
MWH-4     48.533333
MWH-5     63.363636

In [215]:
grp1.agg(np.size)

          MaterialID  Quantity
Location
MWH-1             11        11
MWH-2              9         9
MWH-3              4         4
MWH-4             15        15
MWH-5             11        11

In [216]:
grp1.agg([np.sum, np.mean])

C:\Users\Dell\AppData\Local\Temp\ipykernel_9940\4038976627.py:1: FutureWarning: ['MaterialID'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  grp1.agg([np.sum, np.mean])

         Quantity
              sum       mean
Location
MWH-1         889  80.818182
MWH-2         397  44.111111
MWH-3         174  43.500000
MWH-4         728  48.533333
MWH-5         697  63.363636

In [221]:
r = grp1.agg([np.sum, np.mean])
r

C:\Users\Dell\AppData\Local\Temp\ipykernel_9940\4047264543.py:1: FutureWarning: ['MaterialID'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  r = grp1.agg([np.sum, np.mean])

         Quantity
              sum       mean
Location
MWH-1         889  80.818182
MWH-2         397  44.111111
MWH-3         174  43.500000
MWH-4         728  48.533333
MWH-5         697  63.363636

In [219]:
ind = np.where(r.index == 'MWH-3')
ind

(array([2], dtype=int64),)

In [220]:
r.iloc[ind]

         Quantity
              sum  mean
Location
MWH-3         174  43.5

In [ ]:
# df.drop(df.columns[1], axis=1)

In [3]:
import pandas as pd
ex = pd.read_excel('ERPData.xlsx')
ex.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [14]:
import numpy as np
ind = np.where(ex['Location'].duplicated(keep=False))

In [15]:
ind

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       dtype=int64),)

In [ ]:
import re
a='^([A-Za-z]{5}[0-9]{4}[A-Za-z]{1})$'
b=input("Enter a string to validate:") 
if a==b:
    print("ok")
else:
    print("Not valid")

In [16]:
df = pd.DataFrame(['ERt','PQR'])
df

     0
0  ERt
1  PQR

In [17]:
import re

In [20]:
df.filter(['P'])

Empty DataFrame
Columns: []
Index: [0, 1]

In [ ]:
# a = r'^[a-zA-Z]{5}[0-5]{4}[a-zA-Z]{1}$'
# #pat = re.compile(a)
# for b in pan:
#   if re.match(a,b):
#     print("Valid")
#   else :
#     print("NotValid")
# pan = ['ERTGH1234R',
# 'WERT56348L',
# 'QWERT123TH'
# ]